apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
spec:
  accessModes:
    - ReadWriteOnce
  # local-path is the default StorageClass k3s ships with.
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
